/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-17 at 20:06:30 UTC 
 * Modify at your own risk.
 */

package com.appspot.myapp.formwallApi;

/**
 * Service definition for FormwallApi (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link FormwallApiRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class FormwallApi extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the formwallApi library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "formwallApi/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public FormwallApi(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  FormwallApi(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the FieldTypeEndpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code FormwallApi formwallApi = new FormwallApi(...);}
   *   {@code FormwallApi.FieldTypeEndpoint.List request = formwallApi.fieldTypeEndpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public FieldTypeEndpoint fieldTypeEndpoint() {
    return new FieldTypeEndpoint();
  }

  /**
   * The "fieldTypeEndpoint" collection of methods.
   */
  public class FieldTypeEndpoint {

    /**
     * Create a request for the method "fieldTypeEndpoint.list".
     *
     * This request holds the parameters needed by the formwallApi server.  After setting any optional
     * parameters, call the {@link List#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public List list() throws java.io.IOException {
      List result = new List();
      initialize(result);
      return result;
    }

    public class List extends FormwallApiRequest<com.appspot.myapp.formwallApi.model.FieldTypeCollection> {

      private static final String REST_PATH = "fieldtype";

      /**
       * Create a request for the method "fieldTypeEndpoint.list".
       *
       * This request holds the parameters needed by the the formwallApi server.  After setting any
       * optional parameters, call the {@link List#execute()} method to invoke the remote operation. <p>
       * {@link List#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected List() {
        super(FormwallApi.this, "GET", REST_PATH, null, com.appspot.myapp.formwallApi.model.FieldTypeCollection.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public List setAlt(java.lang.String alt) {
        return (List) super.setAlt(alt);
      }

      @Override
      public List setFields(java.lang.String fields) {
        return (List) super.setFields(fields);
      }

      @Override
      public List setKey(java.lang.String key) {
        return (List) super.setKey(key);
      }

      @Override
      public List setOauthToken(java.lang.String oauthToken) {
        return (List) super.setOauthToken(oauthToken);
      }

      @Override
      public List setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (List) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public List setQuotaUser(java.lang.String quotaUser) {
        return (List) super.setQuotaUser(quotaUser);
      }

      @Override
      public List setUserIp(java.lang.String userIp) {
        return (List) super.setUserIp(userIp);
      }

      @Override
      public List set(String parameterName, Object value) {
        return (List) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the SeedEndpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code FormwallApi formwallApi = new FormwallApi(...);}
   *   {@code FormwallApi.SeedEndpoint.List request = formwallApi.seedEndpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public SeedEndpoint seedEndpoint() {
    return new SeedEndpoint();
  }

  /**
   * The "seedEndpoint" collection of methods.
   */
  public class SeedEndpoint {

    /**
     * Create a request for the method "seedEndpoint.seed".
     *
     * This request holds the parameters needed by the formwallApi server.  After setting any optional
     * parameters, call the {@link Seed#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public Seed seed() throws java.io.IOException {
      Seed result = new Seed();
      initialize(result);
      return result;
    }

    public class Seed extends FormwallApiRequest<Void> {

      private static final String REST_PATH = "seed";

      /**
       * Create a request for the method "seedEndpoint.seed".
       *
       * This request holds the parameters needed by the the formwallApi server.  After setting any
       * optional parameters, call the {@link Seed#execute()} method to invoke the remote operation. <p>
       * {@link Seed#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected Seed() {
        super(FormwallApi.this, "POST", REST_PATH, null, Void.class);
      }

      @Override
      public Seed setAlt(java.lang.String alt) {
        return (Seed) super.setAlt(alt);
      }

      @Override
      public Seed setFields(java.lang.String fields) {
        return (Seed) super.setFields(fields);
      }

      @Override
      public Seed setKey(java.lang.String key) {
        return (Seed) super.setKey(key);
      }

      @Override
      public Seed setOauthToken(java.lang.String oauthToken) {
        return (Seed) super.setOauthToken(oauthToken);
      }

      @Override
      public Seed setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Seed) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Seed setQuotaUser(java.lang.String quotaUser) {
        return (Seed) super.setQuotaUser(quotaUser);
      }

      @Override
      public Seed setUserIp(java.lang.String userIp) {
        return (Seed) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.Boolean clear;

      /**

       */
      public java.lang.Boolean getClear() {
        return clear;
      }

      public Seed setClear(java.lang.Boolean clear) {
        this.clear = clear;
        return this;
      }

      @Override
      public Seed set(String parameterName, Object value) {
        return (Seed) super.set(parameterName, value);
      }
    }

  }

  /**
   * An accessor for creating requests from the UserEndpoint collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code FormwallApi formwallApi = new FormwallApi(...);}
   *   {@code FormwallApi.UserEndpoint.List request = formwallApi.userEndpoint().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public UserEndpoint userEndpoint() {
    return new UserEndpoint();
  }

  /**
   * The "userEndpoint" collection of methods.
   */
  public class UserEndpoint {

    /**
     * Create a request for the method "userEndpoint.register".
     *
     * This request holds the parameters needed by the formwallApi server.  After setting any optional
     * parameters, call the {@link Register#execute()} method to invoke the remote operation.
     *
     * @param email
     * @return the request
     */
    public Register register(java.lang.String email) throws java.io.IOException {
      Register result = new Register(email);
      initialize(result);
      return result;
    }

    public class Register extends FormwallApiRequest<com.appspot.myapp.formwallApi.model.Session> {

      private static final String REST_PATH = "register/{email}";

      /**
       * Create a request for the method "userEndpoint.register".
       *
       * This request holds the parameters needed by the the formwallApi server.  After setting any
       * optional parameters, call the {@link Register#execute()} method to invoke the remote operation.
       * <p> {@link
       * Register#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param email
       * @since 1.13
       */
      protected Register(java.lang.String email) {
        super(FormwallApi.this, "POST", REST_PATH, null, com.appspot.myapp.formwallApi.model.Session.class);
        this.email = com.google.api.client.util.Preconditions.checkNotNull(email, "Required parameter email must be specified.");
      }

      @Override
      public Register setAlt(java.lang.String alt) {
        return (Register) super.setAlt(alt);
      }

      @Override
      public Register setFields(java.lang.String fields) {
        return (Register) super.setFields(fields);
      }

      @Override
      public Register setKey(java.lang.String key) {
        return (Register) super.setKey(key);
      }

      @Override
      public Register setOauthToken(java.lang.String oauthToken) {
        return (Register) super.setOauthToken(oauthToken);
      }

      @Override
      public Register setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Register) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Register setQuotaUser(java.lang.String quotaUser) {
        return (Register) super.setQuotaUser(quotaUser);
      }

      @Override
      public Register setUserIp(java.lang.String userIp) {
        return (Register) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String email;

      /**

       */
      public java.lang.String getEmail() {
        return email;
      }

      public Register setEmail(java.lang.String email) {
        this.email = email;
        return this;
      }

      @Override
      public Register set(String parameterName, Object value) {
        return (Register) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link FormwallApi}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link FormwallApi}. */
    @Override
    public FormwallApi build() {
      return new FormwallApi(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link FormwallApiRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setFormwallApiRequestInitializer(
        FormwallApiRequestInitializer formwallapiRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(formwallapiRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
