/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-17 at 20:06:30 UTC 
 * Modify at your own risk.
 */

package com.appspot.myapp.formwallApi.model;

/**
 * Model definition for FieldType.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the formwallApi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class FieldType extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String htmlType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String regexValidator;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getHtmlType() {
    return htmlType;
  }

  /**
   * @param htmlType htmlType or {@code null} for none
   */
  public FieldType setHtmlType(java.lang.String htmlType) {
    this.htmlType = htmlType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public FieldType setId(Key id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getRegexValidator() {
    return regexValidator;
  }

  /**
   * @param regexValidator regexValidator or {@code null} for none
   */
  public FieldType setRegexValidator(java.lang.String regexValidator) {
    this.regexValidator = regexValidator;
    return this;
  }

  @Override
  public FieldType set(String fieldName, Object value) {
    return (FieldType) super.set(fieldName, value);
  }

  @Override
  public FieldType clone() {
    return (FieldType) super.clone();
  }

}
