/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-08-17 at 20:06:30 UTC 
 * Modify at your own risk.
 */

package com.appspot.myapp.formwallApi.model;

/**
 * Model definition for Session.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the formwallApi. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Session extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String authCode;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime expiration;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key userId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAuthCode() {
    return authCode;
  }

  /**
   * @param authCode authCode or {@code null} for none
   */
  public Session setAuthCode(java.lang.String authCode) {
    this.authCode = authCode;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getExpiration() {
    return expiration;
  }

  /**
   * @param expiration expiration or {@code null} for none
   */
  public Session setExpiration(com.google.api.client.util.DateTime expiration) {
    this.expiration = expiration;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Session setId(Key id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public Session setUserId(Key userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public Session set(String fieldName, Object value) {
    return (Session) super.set(fieldName, value);
  }

  @Override
  public Session clone() {
    return (Session) super.clone();
  }

}
